plugins {
    id 'application'
}

group = 'com.example'
version = '1.0.0'

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.telegram:telegrambots:6.9.7.1'
    implementation 'org.yaml:snakeyaml:2.2'
}

application {
    mainClass = 'com.example.wg.Main'
}

jar {
    manifest {
        attributes 'Main-Class': application.mainClass.get()
    }
}

tasks.register('fatJar', Jar) {
    archiveClassifier = 'all'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from sourceSets.main.output
    dependsOn configurations.runtimeClasspath
    from {
        configurations.runtimeClasspath.get().collect { it.isDirectory() ? it : zipTree(it) }
    }
    manifest {
        attributes 'Main-Class': application.mainClass.get()
    }
}
